#!/bin/bash

# make sure your latest code has been pushed to git

docker build -t dsjoerg/scoreserver combine/$name/scoreserver && \
docker tag -f dsjoerg/scoreserver tutum.co/dsjoerg/scoreserver && \
docker push tutum.co/dsjoerg/scoreserver

docker images | grep scoreserver

/usr/local/bin/boot2docker ssh sudo ntpclient -s -h pool.ntp.org
