#!/bin/bash

# make sure your latest code has been pushed to git

docker build -t dsjoerg/fun .
docker tag dsjoerg/fun tutum.co/dsjoerg/fun
docker push tutum.co/dsjoerg/fun

/usr/local/bin/boot2docker ssh sudo ntpclient -s -h pool.ntp.org
