#!/bin/bash

MY_PATH="`dirname \"$0\"`"

docker build -t 'dsjoerg/blundercheck' $MY_PATH/.. 2>&1 | grep "Success"

docker run -ti -v /Users/david/Dropbox/Programming/pystockfish:/usr/local/src/pystockfish \
               -v /Users/david/Dropbox/Programming/blundercheck:/usr/local/src/blundercheck \
       dsjoerg/blundercheck python
